# -*- coding: utf-8 -*-
"""T-20 World Cup 2022 Data Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NHtDgF25YNDJZ2c31AbGLA1QrEe2Q_Yo
"""

import numpy as np
import pandas as pd

data=pd.read_csv("/content/drive/MyDrive/Cricket Analysis/T-20 World cup 2022.csv")

data

data.info()

print(data.isnull().sum())

data['home_team'].value_counts()

# Separate data for each home team
INDIA_data = data[data["home_team"] == "INDIA"]
NZ_data = data[data["home_team"] == "NZ"]
SL_data = data[data["home_team"] == "SL"]
ZIM_data = data[data["home_team"] == "ZIM"]
BAN_data = data[data["home_team"] == "BAN"]
SCOT_data = data[data["home_team"] == "SCOT"]
PAK_data = data[data["home_team"] == "PAK"]
UAE_data = data[data["home_team"] == "UAE"]
NAM_data = data[data["home_team"] == "NAM"]
AUS_data = data[data["home_team"] == "AUS"]
AFG_data = data[data["home_team"] == "AFG"]
WI_data = data[data["home_team"] == "WI"]
NED_data = data[data["home_team"] == "NED"]
IRE_data = data[data["home_team"] == "IRE"]
ENG_data = data[data["home_team"] == "ENG"]
SA_data = data[data["home_team"] == "SA"]

# Calculate total runs for each team
total_runs_INDIA = INDIA_data["runs"].sum()
total_runs_NZ = NZ_data["runs"].sum()
total_runs_SL = SL_data["runs"].sum()
total_runs_ZIM = ZIM_data["runs"].sum()
total_runs_BAN = BAN_data["runs"].sum()
total_runs_SCOT = SCOT_data["runs"].sum()
total_runs_PAK = PAK_data["runs"].sum()
total_runs_UAE = UAE_data["runs"].sum()
total_runs_NAM = NAM_data["runs"].sum()
total_runs_AUS = AUS_data["runs"].sum()
total_runs_AFG = AFG_data["runs"].sum()
total_runs_WI = WI_data["runs"].sum()
total_runs_NED = NED_data["runs"].sum()
total_runs_IRE = IRE_data["runs"].sum()
total_runs_ENG = ENG_data["runs"].sum()
total_runs_SA = SA_data["runs"].sum()

# Create a DataFrame with team names and total runs
home_team_runs_df = pd.DataFrame({
    "Team": ["INDIA", "NZ", "SL", "ZIM", "BAN", "SCOT", "PAK", "UAE", "NAM", "AUS", "AFG", "WI", "NED", "IRE","ENG", "SA"],
    "Runs": [total_runs_INDIA, total_runs_NZ, total_runs_SL, total_runs_ZIM, total_runs_BAN, total_runs_SCOT, total_runs_PAK, total_runs_UAE, total_runs_NAM, total_runs_AUS, total_runs_AFG, total_runs_WI, total_runs_NED, total_runs_IRE, total_runs_ENG, total_runs_SA]
})

"""# Most runs scored home team"""

home_sort=home_team_runs_df.sort_values(by="Runs", ascending= False)
home_sort

import matplotlib.pyplot as plt

plt.plot(home_sort["Team"], home_sort["Runs"])

data['away_team'].value_counts()

# Separate data for each away team
INDIA_data = data[data["away_team"] == "INDIA"]
NZ_data = data[data["away_team"] == "NZ"]
SL_data = data[data["away_team"] == "SL"]
ZIM_data = data[data["away_team"] == "ZIM"]
BAN_data = data[data["away_team"] == "BAN"]
SCOT_data = data[data["away_team"] == "SCOT"]
PAK_data = data[data["away_team"] == "PAK"]
UAE_data = data[data["away_team"] == "UAE"]
NAM_data = data[data["away_team"] == "NAM"]
AUS_data = data[data["away_team"] == "AUS"]
AFG_data = data[data["away_team"] == "AFG"]
WI_data = data[data["away_team"] == "WI"]
NED_data = data[data["away_team"] == "NED"]
IRE_data = data[data["away_team"] == "IRE"]
ENG_data = data[data["away_team"] == "ENG"]
SA_data = data[data["away_team"] == "SA"]

# Calculate total runs for each team
total_runs_INDIA = INDIA_data["runs"].sum()
total_runs_NZ = NZ_data["runs"].sum()
total_runs_SL = SL_data["runs"].sum()
total_runs_ZIM = ZIM_data["runs"].sum()
total_runs_BAN = BAN_data["runs"].sum()
total_runs_SCOT = SCOT_data["runs"].sum()
total_runs_PAK = PAK_data["runs"].sum()
total_runs_UAE = UAE_data["runs"].sum()
total_runs_NAM = NAM_data["runs"].sum()
total_runs_AUS = AUS_data["runs"].sum()
total_runs_AFG = AFG_data["runs"].sum()
total_runs_WI = WI_data["runs"].sum()
total_runs_NED = NED_data["runs"].sum()
total_runs_IRE = IRE_data["runs"].sum()
total_runs_ENG = ENG_data["runs"].sum()
total_runs_SA = SA_data["runs"].sum()

# Create a DataFrame with team names and total runs
away_team_runs_df = pd.DataFrame({
    "Team": ["INDIA", "NZ", "SL", "ZIM", "BAN", "SCOT", "PAK", "UAE", "NAM", "AUS", "AFG", "WI", "NED", "IRE","ENG", "SA"],
    "Runs": [total_runs_INDIA, total_runs_NZ, total_runs_SL, total_runs_ZIM, total_runs_BAN, total_runs_SCOT, total_runs_PAK, total_runs_UAE, total_runs_NAM, total_runs_AUS, total_runs_AFG, total_runs_WI, total_runs_NED, total_runs_IRE, total_runs_ENG, total_runs_SA]
})

"""# most runs scored away team"""

away_sort=away_team_runs_df.sort_values(by="Runs", ascending= False)
away_sort

plt.plot(away_sort["Team"], home_sort["Runs"])

home_away_runs_data = pd.merge(home_team_runs_df, away_team_runs_df, on="Team")

home_away_runs_data

home_away_runs_data = home_away_runs_data.rename(columns={"Runs_x": "Runs_Home", "Runs_y": "Runs_Away"})

home_away_runs_data

# Create the third column containing the sum of Runs_Home and Runs_Away
home_away_runs_data["Total_Runs"] = home_away_runs_data["Runs_Home"] + home_away_runs_data["Runs_Away"]

"""# Most runs scored team"""

sorted_data=home_away_runs_data.sort_values(by="Total_Runs", ascending=False)
sorted_data

plt.plot(sorted_data["Team"], sorted_data["Total_Runs"])

# Mark rows where a boundary was hit
data.loc[data['shortText'].str.contains('4 runs|6 runs'), 'isBoundary'] = True

# Count the number of boundaries hit by each team
boundary_counts = data.groupby(['home_team', 'away_team'])['isBoundary'].sum()

boundary_counts

boundary_by_teams=pd.DataFrame(boundary_counts)

"""# Number of Boundaries hits by each time against each team"""

boundary_by_teams

boundaries=boundary_by_teams.reset_index()
boundaries

boundaries=boundaries.rename(columns= {"isBoundary": "Boundaries"})
boundaries=boundaries[['home_team','Boundaries']]
boundaries

# Group by team and sum the total boundaries hit
total_boundaries_by_team = boundaries.groupby("home_team").sum()
boundary_sorted=total_boundaries_by_team.sort_values(by="Boundaries", ascending=False)
boundary_sorted

"""# Total number of Boundaries scored by each team"""

plt.plot(boundary_sorted['Boundaries'], boundary_sorted.index)